spring.application.name=scout_backend
spring.datasource.url=jdbc:postgresql://dpg-d7rdn1lckfvc73a0gef0-a.singapore-postgres.render.com:5432/hr_db_svdq
spring.datasource.username=hr_db_svdq_user
spring.datasource.password=kB9gP3J3Lw8nrzau1XhAJvyi1IWEWZmi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.data.jpa.repository.query=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Swagger UI: http://localhost:8080/

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# CORS - comma separated origins allowed to call backend APIs (development)
app.cors.allowed-origins=http://localhost:3000
