spring.application.name=scout_backend
spring.datasource.url=jdbc:postgresql://dpg-d8jef8j7uimc73bkpc9g-a.singapore-postgres.render.com:5432/scout_db_68kx
#spring.datasource.url=jdbc:postgresql://dpg-d7rdn1lckfvc73a0gef0-a.singapore-postgres.render.com:5432/scout_db_68kx

# postgresql://scout_db_68kx_user:o0zJhSCmfgLfRzKC1wVBkNq3O1C0dcDY@dpg-d8jef8j7uimc73bkpc9g-a.singapore-postgres.render.com/scout_db_68kx

spring.datasource.username=scout_db_68kx_user
spring.datasource.password=o0zJhSCmfgLfRzKC1wVBkNq3O1C0dcDY
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.data.jpa.repository.query=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Swagger UI: http://localhost:8080/

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# CORS - comma separated origins allowed to call backend APIs (development)
app.cors.allowed-origins=http://localhost:3000
